DELETE  http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzY4MjYwNDMxLCJ1c2VySWQiOjF9.E1OoEEQyeTfj2EpQzG4F5RpvUU4kRyXKduhhciW1DGg